### ISSUE TITLE
Types of Trends: Seasonal

### ISSUE THREAD

**Issue by FerdinandBeaman** [learn-co-curriculum/dsc-types-of-trends#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6224/assignments/226896?module_item_id=530139

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ x] Instructions unclear
- [ ] Other (explain below)

### Source

```
This lesson doesn't make it clear that seasonal trends count against stationarity. If anything, the graphics near the beginning of the lesson led me to believe that seasonal trends were fine, thanks to the regularity of the cycle shown in the graph. It was only in a later lesson when they described differencing that I realized seasonal trends might not be ok.
```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for this note. For this case, please reach out to your instructor regarding any clarification that you need.
